server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/mkdown?serverTimezone=GMT%2B8&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 123456

  messages:
    basename: messages

  main:
    allow-bean-definition-overriding: true
Qiniu:
  AccessKey:
    c07IdeJTcsMr0b23Dqw6Ay75wsVQZ5jzTsdJrIfC
  SecretKey:
    OnvK6tKv4lAidtRh3aGX6LUdM4geHVxOWoC4O-j6
  
mybatis-plus:
  mapper-locations:  classpath:/Mapper/**/*Mapper.xml
  type-aliases-package: com.example.mkdown_java.*.model
  configuration:
    jdbc-type-for-null: 'null'
    call-setters-on-nulls: true